# Generated by Django 4.2.7 on 2023-11-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_numb', models.PositiveIntegerField(verbose_name='Кадастровый номер')),
                ('latitude', models.FloatField(help_text='Введите широту', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Введите долготу', verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_or_f', models.BooleanField(verbose_name='Правда или нет')),
                ('coordinates', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastral.coordinates', verbose_name='Координаты')),
            ],
        ),
    ]
